language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
          - gcc-6
          - g++-6
          - libfftw3-dev
          - libsamplerate0-dev
          - libaudiofile-dev
          - libsndfile1-dev
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
      env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

  - os: linux
    dist: xenial
    sudo: true
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-7
        - g++-7
        - libfftw3-dev
        - libsamplerate0-dev
        - libaudiofile-dev
        - libsndfile1-dev
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
    env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
- mkdir -p build
- cd build
- cmake -DBUILD_TESTS=ON -DBUILD_DOCS=ON -DBUILD_EXAMPLES=ON ..
- make -j4
- make test