language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      sudo: true
      compiler: clang
      addons:
        homebrew:
          packages:
          - cmake
          - fftw
          - libsamplerate
          - libsndfile
          - boost
          - boost-python
          - python
          - numpy
          - scipy
          - lcov

branches:
  only:
  - master

env:
  global:
    - CODECOV_TOKEN =: "69069f21-5a1a-4d45-a6c2-e7a5af9bd63d"

notifications:
  email: false

script:
  - cd ${TRAVIS_BUILD_DIR}
  - sh travis.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)
